[build]
  functions = "netlify/functions"

# 1. Microservicio de AUTH
[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/auth"
  status = 200

# 2. Microservicio de PRUEBA (Status)
[[redirects]]
  from = "/status/*"
  to = "/.netlify/functions/prueba"
  status = 200

# 3. Microservicio GATEWAY (Principal)
[[redirects]]
  from = "/gateway/*"
  to = "/.netlify/functions/gateway"
  status = 200
