- name: Copy config to VPS (SCP)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_GATEWAY }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "gateway/microservicios"
          target: "/home/proyecto"
          strip_components: 1