name: Deploy Multi-VPS
on:
  push:
    branches: [ main ]

jobs:
  deploy-gateway:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Nginx Config (VPS 1)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_GATEWAY }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Ahora buscamos el archivo dentro de la carpeta gateway/
            sudo cp /home/proyecto/gateway/microservicios /etc/nginx/conf.d/
            sudo service nginx restart

  deploy-auth:
    needs: deploy-gateway
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Auth Service (VPS 2)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_AUTH_SERVICE }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/proyecto/auth-service
            git pull origin main
            pm2 restart auth-service.js